create table users (
	id bigint generated by default as identity primary key,
	display_name varchar(50) not null,
	created_at timestamptz not null,
	updated_at timestamptz not null
);

create table scenarios (
	id bigint generated by default as identity primary key,
	title varchar(100) not null,
	summary varchar(255) not null,
	description text not null,
	category varchar(50) not null,
	difficulty varchar(50) not null,
	created_at timestamptz not null,
	updated_at timestamptz not null,
	constraint ck_scenarios_category
		check (category in ('SPRING_BOOT_RUNTIME', 'DATABASE', 'QUEUE')),
	constraint ck_scenarios_difficulty
		check (difficulty in ('BEGINNER', 'INTERMEDIATE', 'ADVANCED'))
);

create table scenario_specs (
	id bigint generated by default as identity primary key,
	scenario_id bigint not null,
	image_ref varchar(255) not null,
	created_at timestamptz not null,
	updated_at timestamptz not null,
	constraint fk_scenario_specs_scenario
		foreign key (scenario_id) references scenarios (id)
);

create table scenario_runs (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	scenario_id bigint not null,
	status varchar(50) not null,
	started_at timestamptz not null,
	completed_at timestamptz,
	last_accessed_at timestamptz not null,
	created_at timestamptz not null,
	updated_at timestamptz not null,
	constraint fk_scenario_runs_user
		foreign key (user_id) references users (id),
	constraint fk_scenario_runs_scenario
		foreign key (scenario_id) references scenarios (id),
	constraint ck_scenario_runs_status
		check (status in ('ACTIVE', 'COMPLETED', 'BROKEN', 'ABANDONED', 'EXPIRED'))
);

create table sandboxes (
	id bigint generated by default as identity primary key,
	scenario_run_id bigint not null,
	scenario_spec_id bigint not null,
	status varchar(50) not null,
	workspace_path varchar(500) not null,
	created_at timestamptz not null,
	updated_at timestamptz not null,
	constraint uq_sandboxes_scenario_run unique (scenario_run_id),
	constraint fk_sandboxes_scenario_run
		foreign key (scenario_run_id) references scenario_runs (id),
	constraint fk_sandboxes_scenario_spec
		foreign key (scenario_spec_id) references scenario_specs (id),
	constraint ck_sandboxes_status
		check (status in ('PROVISIONING', 'RUNNING', 'STOPPED', 'BROKEN', 'DESTROYED'))
);

create index ix_scenario_specs_scenario_id
	on scenario_specs (scenario_id);

create index ix_scenario_runs_user_id
	on scenario_runs (user_id);

create index ix_scenario_runs_scenario_id
	on scenario_runs (scenario_id);

create unique index uq_active_scenario_runs_user_scenario
	on scenario_runs (user_id, scenario_id)
	where status = 'ACTIVE';

create index ix_sandboxes_scenario_spec_id
	on sandboxes (scenario_spec_id);
